name: 'XORAS Release Integrity Sentry'
description: 'Enforce environment integrity and prevent broken deployments caused by missing variables.'
author: 'XORAS Engineering'
inputs:
  path:
    description: 'The path to the repository to audit'
    required: false
    default: '.'
  upload-url:
    description: 'Telemetry server URL to transmit reports to'
    required: false
  no-verify:
    description: 'Set to true to skip SHA-256 integrity verification'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'green'
